extends Node

var full_key_list = preload("full_key_list.gd")

var FullKeyList = full_key_list.FullKeyList

var keyListLowercase = {
	"A":FullKeyList.KEY_A,
	"B":FullKeyList.KEY_B,
	"C":FullKeyList.KEY_C,
	"D":FullKeyList.KEY_D,
	"E":FullKeyList.KEY_E,
	"F":FullKeyList.KEY_F,
	"G":FullKeyList.KEY_G,
	"H":FullKeyList.KEY_H,
	"I":FullKeyList.KEY_I,
	"J":FullKeyList.KEY_J,
	"K":FullKeyList.KEY_K,
	"L":FullKeyList.KEY_L,
	"M":FullKeyList.KEY_M,
	"N":FullKeyList.KEY_N,
	"O":FullKeyList.KEY_O,
	"P":FullKeyList.KEY_P,
	"Q":FullKeyList.KEY_Q,
	"R":FullKeyList.KEY_R,
	"S":FullKeyList.KEY_S,
	"T":FullKeyList.KEY_T,
	"U":FullKeyList.KEY_U,
	"V":FullKeyList.KEY_V,
	"W":FullKeyList.KEY_W,
	"X":FullKeyList.KEY_X,
	"Y":FullKeyList.KEY_Y,
	"Z":FullKeyList.KEY_Z,
	"à":FullKeyList.KEY_AGRAVE,
	"á":FullKeyList.KEY_AACUTE,
	"â":FullKeyList.KEY_ACIRCUMFLEX,
	"ã":FullKeyList.KEY_ATILDE,
	"ä":196,
	"å":FullKeyList.KEY_ARING,
	"æ":FullKeyList.KEY_AE,
	"ç":FullKeyList.KEY_CCEDILLA,
	"è":FullKeyList.KEY_EGRAVE,
	"é":FullKeyList.KEY_EACUTE,
	"ê":FullKeyList.KEY_ECIRCUMFLEX,
	"ë":FullKeyList.KEY_EDIAERESIS,
	"ì":FullKeyList.KEY_IGRAVE,
	"í":FullKeyList.KEY_IACUTE,
	"î":FullKeyList.KEY_ICIRCUMFLEX,
	"ð":FullKeyList.KEY_ETH,
	"ñ":FullKeyList.KEY_NTILDE,
	"ò":FullKeyList.KEY_OGRAVE,
	"ó":FullKeyList.KEY_OACUTE,
	"ô":FullKeyList.KEY_OCIRCUMFLEX,
	"õ":FullKeyList.KEY_OTILDE,
	"ö":214,
	"ø":FullKeyList.KEY_OOBLIQUE,
	"ù":FullKeyList.KEY_UGRAVE,
	"ú":FullKeyList.KEY_UACUTE,
	"û":FullKeyList.KEY_UCIRCUMFLEX,
	"ü":220,
	"ý":FullKeyList.KEY_YACUTE,
	"ÿ":FullKeyList.KEY_YDIAERESIS,
}

var keyListUnicode = {
	"Escape":FullKeyList.KEY_ESCAPE,
	"Tab":FullKeyList.KEY_TAB,
	"Shift-Tab":FullKeyList.KEY_BACKTAB,
	"Backspace":FullKeyList.KEY_BACKSPACE,
	"Return":FullKeyList.KEY_ENTER,
	"Enter":FullKeyList.KEY_KP_ENTER,
	"Insert":FullKeyList.KEY_INSERT,
	"Delete":FullKeyList.KEY_DELETE,
	"Pause":FullKeyList.KEY_PAUSE,
	"Printscreen":FullKeyList.KEY_PRINT,
	"SystemRequest":FullKeyList.KEY_SYSREQ,
	"Clear":FullKeyList.KEY_CLEAR,
	"Home":FullKeyList.KEY_HOME,
	"End":FullKeyList.KEY_END,
	"LeftArrow":FullKeyList.KEY_LEFT,
	"UpArrow":FullKeyList.KEY_UP,
	"RightArrow":FullKeyList.KEY_RIGHT,
	"DownArrow":FullKeyList.KEY_DOWN,
	"Pageup":FullKeyList.KEY_PAGEUP,
	"Pagedown":FullKeyList.KEY_PAGEDOWN,
	"Shift":FullKeyList.KEY_SHIFT,
	"Control":KEY_CTRL,
	"Meta":KEY_META,
	"Alt":KEY_ALT,
	"Capslock":FullKeyList.KEY_CAPSLOCK,
	"Numlock":FullKeyList.KEY_NUMLOCK,
	"Scrolllock":FullKeyList.KEY_SCROLLLOCK,
	"F1":FullKeyList.KEY_F1,
	"F2":FullKeyList.KEY_F2,
	"F3":FullKeyList.KEY_F3,
	"F4":FullKeyList.KEY_F4,
	"F5":FullKeyList.KEY_F5,
	"F6":FullKeyList.KEY_F6,
	"F7":FullKeyList.KEY_F7,
	"F8":FullKeyList.KEY_F8,
	"F9":FullKeyList.KEY_F9,
	"F10":FullKeyList.KEY_F10,
	"F11":FullKeyList.KEY_F11,
	"F12":FullKeyList.KEY_F12,
	"F13":FullKeyList.KEY_F13,
	"F14":FullKeyList.KEY_F14,
	"F15":FullKeyList.KEY_F15,
	"F16":FullKeyList.KEY_F16,
	"MultiplyonNumpad":FullKeyList.KEY_KP_MULTIPLY,
	"DivideonNumpad":FullKeyList.KEY_KP_DIVIDE,
	"SubtractonNumpad":FullKeyList.KEY_KP_SUBTRACT,
	"PeriodonNumpad":FullKeyList.KEY_KP_PERIOD,
	"AddonNumpad":FullKeyList.KEY_KP_ADD,
	"Number0onNumpad":FullKeyList.KEY_KP_0,
	"Number1onNumpad":FullKeyList.KEY_KP_1,
	"Number2onNumpad":FullKeyList.KEY_KP_2,
	"Number3onNumpad":FullKeyList.KEY_KP_3,
	"Number4onNumpad":FullKeyList.KEY_KP_4,
	"Number5onNumpad":FullKeyList.KEY_KP_5,
	"Number6onNumpad":FullKeyList.KEY_KP_6,
	"Number7onNumpad":FullKeyList.KEY_KP_7,
	"Number8onNumpad":FullKeyList.KEY_KP_8,
	"Number9onNumpad":FullKeyList.KEY_KP_9,
	"LeftSuper(Windows)":FullKeyList.KEY_MENU,
	"LeftHyper":FullKeyList.KEY_HYPER_L,
	"RightHyper":FullKeyList.KEY_HYPER_R,
	"Help":FullKeyList.KEY_HELP,
	"LeftDirection":FullKeyList.KEY_DIRECTION_L,
	"RightDirection":FullKeyList.KEY_DIRECTION_R,
	"Back":FullKeyList.KEY_BACK,
	"Forward":FullKeyList.KEY_FORWARD,
	"Stop":FullKeyList.KEY_STOP,
	"Refresh":FullKeyList.KEY_REFRESH,
	"Volumedown":FullKeyList.KEY_VOLUMEDOWN,
	"Mutevolume":FullKeyList.KEY_VOLUMEMUTE,
	"Volumeup":FullKeyList.KEY_VOLUMEUP,
	"BassBoost":FullKeyList.KEY_BASSBOOST,
	"BassUp":FullKeyList.KEY_BASSUP,
	"BassDown":FullKeyList.KEY_BASSDOWN,
	"TrebleUp":FullKeyList.KEY_TREBLEUP,
	"TrebleDown":FullKeyList.KEY_TREBLEDOWN,
	"Mediaplay":FullKeyList.KEY_MEDIAPLAY,
	"Mediastop":FullKeyList.KEY_MEDIASTOP,
	"Previoussong":FullKeyList.KEY_MEDIAPREVIOUS,
	"Nextsong":FullKeyList.KEY_MEDIANEXT,
	"Mediarecord":FullKeyList.KEY_MEDIARECORD,
	"Homepage":FullKeyList.KEY_HOMEPAGE,
	"Favorites":FullKeyList.KEY_FAVORITES,
	"Search":FullKeyList.KEY_SEARCH,
	"Standby":FullKeyList.KEY_STANDBY,
	"OpenURL/LaunchBrowser":FullKeyList.KEY_OPENURL,
	"LaunchMail":FullKeyList.KEY_LAUNCHMAIL,
	"LaunchMedia":FullKeyList.KEY_LAUNCHMEDIA,
	"LaunchShortcut0":FullKeyList.KEY_LAUNCH0,
	"LaunchShortcut1":FullKeyList.KEY_LAUNCH1,
	"LaunchShortcut2":FullKeyList.KEY_LAUNCH2,
	"LaunchShortcut3":FullKeyList.KEY_LAUNCH3,
	"LaunchShortcut4":FullKeyList.KEY_LAUNCH4,
	"LaunchShortcut5":FullKeyList.KEY_LAUNCH5,
	"LaunchShortcut6":FullKeyList.KEY_LAUNCH6,
	"LaunchShortcut7":FullKeyList.KEY_LAUNCH7,
	"LaunchShortcut8":FullKeyList.KEY_LAUNCH8,
	"LaunchShortcut9":FullKeyList.KEY_LAUNCH9,
	"LaunchShortcutA":FullKeyList.KEY_LAUNCHA,
	"LaunchShortcutB":FullKeyList.KEY_LAUNCHB,
	"LaunchShortcutC":FullKeyList.KEY_LAUNCHC,
	"LaunchShortcutD":FullKeyList.KEY_LAUNCHD,
	"LaunchShortcutE":FullKeyList.KEY_LAUNCHE,
	"LaunchShortcutF":FullKeyList.KEY_LAUNCHF,
	"Unknown":FullKeyList.KEY_UNKNOWN,
	"Space":FullKeyList.KEY_SPACE,
	"!":FullKeyList.KEY_EXCLAM,
	"\"":FullKeyList.KEY_QUOTEDBL,
	"#":FullKeyList.KEY_NUMBERSIGN,
	"$":FullKeyList.KEY_DOLLAR,
	"%":FullKeyList.KEY_PERCENT,
	"&":FullKeyList.KEY_AMPERSAND,
	"'":FullKeyList.KEY_APOSTROPHE,
	"(":FullKeyList.KEY_PARENLEFT,
	")":FullKeyList.KEY_PARENRIGHT,
	"*":FullKeyList.KEY_ASTERISK,
	"+":FullKeyList.KEY_PLUS,
	",":FullKeyList.KEY_COMMA,
	"-":FullKeyList.KEY_MINUS,
	".":FullKeyList.KEY_PERIOD,
	"/":FullKeyList.KEY_SLASH,
	"0":FullKeyList.KEY_0,
	"1":FullKeyList.KEY_1,
	"2":FullKeyList.KEY_2,
	"3":FullKeyList.KEY_3,
	"4":FullKeyList.KEY_4,
	"5":FullKeyList.KEY_5,
	"6":FullKeyList.KEY_6,
	"7":FullKeyList.KEY_7,
	"8":FullKeyList.KEY_8,
	"9":FullKeyList.KEY_9,
	":":FullKeyList.KEY_COLON,
	";":FullKeyList.KEY_SEMICOLON,
	"<":FullKeyList.KEY_LESS,
	"=":FullKeyList.KEY_EQUAL,
	">":FullKeyList.KEY_GREATER,
	"?":FullKeyList.KEY_QUESTION,
	"@":FullKeyList.KEY_AT,
	"A":FullKeyList.KEY_A,
	"B":FullKeyList.KEY_B,
	"C":FullKeyList.KEY_C,
	"D":FullKeyList.KEY_D,
	"E":FullKeyList.KEY_E,
	"F":FullKeyList.KEY_F,
	"G":FullKeyList.KEY_G,
	"H":FullKeyList.KEY_H,
	"I":FullKeyList.KEY_I,
	"J":FullKeyList.KEY_J,
	"K":FullKeyList.KEY_K,
	"L":FullKeyList.KEY_L,
	"M":FullKeyList.KEY_M,
	"N":FullKeyList.KEY_N,
	"O":FullKeyList.KEY_O,
	"P":FullKeyList.KEY_P,
	"Q":FullKeyList.KEY_Q,
	"R":FullKeyList.KEY_R,
	"S":FullKeyList.KEY_S,
	"T":FullKeyList.KEY_T,
	"U":FullKeyList.KEY_U,
	"V":FullKeyList.KEY_V,
	"W":FullKeyList.KEY_W,
	"X":FullKeyList.KEY_X,
	"Y":FullKeyList.KEY_Y,
	"Z":FullKeyList.KEY_Z,
	"[":FullKeyList.KEY_BRACKETLEFT,
	"\\":FullKeyList.KEY_BACKSLASH,
	"]":FullKeyList.KEY_BRACKETRIGHT,
	"^":FullKeyList.KEY_ASCIICIRCUM,
	"_":FullKeyList.KEY_UNDERSCORE,
	"LeftQuote":FullKeyList.KEY_QUOTELEFT,
	"{":FullKeyList.KEY_BRACELEFT,
	"|":FullKeyList.KEY_BAR,
	"}":FullKeyList.KEY_BRACERIGHT,
	"~":FullKeyList.KEY_ASCIITILDE,
	"NoBreakSpace":FullKeyList.KEY_NOBREAKSPACE,
	"ExcalmDown":FullKeyList.KEY_EXCLAMDOWN,
	"¢":FullKeyList.KEY_CENT,
	"Sterling":FullKeyList.KEY_STERLING,
	"Currency":FullKeyList.KEY_CURRENCY,
	"Yen":FullKeyList.KEY_YEN,
	"¦":FullKeyList.KEY_BROKENBAR,
	"§":FullKeyList.KEY_SECTION,
	"¨":FullKeyList.KEY_DIAERESIS,
	"©":FullKeyList.KEY_COPYRIGHT,
	"Feminine":FullKeyList.KEY_ORDFEMININE,
	"«":FullKeyList.KEY_GUILLEMOTLEFT,
	"»":FullKeyList.KEY_NOTSIGN,
	"‐":FullKeyList.KEY_HYPHEN,
	"®":FullKeyList.KEY_REGISTERED,
	"Macron":FullKeyList.KEY_MACRON,
	"°":FullKeyList.KEY_DEGREE,
	"±":FullKeyList.KEY_PLUSMINUS,
	"²":FullKeyList.KEY_TWOSUPERIOR,
	"³":FullKeyList.KEY_THREESUPERIOR,
	"´":FullKeyList.KEY_ACUTE,
	"µ":FullKeyList.KEY_MU,
	"Paragraph":FullKeyList.KEY_PARAGRAPH,
	"·":FullKeyList.KEY_PERIODCENTERED,
	"¬":FullKeyList.KEY_CEDILLA,
	"¹":FullKeyList.KEY_ONESUPERIOR,
	"♂":FullKeyList.KEY_MASCULINE,
	"GuillemotRight":FullKeyList.KEY_GUILLEMOTRIGHT,
	"¼":FullKeyList.KEY_ONEQUARTER,
	"½":FullKeyList.KEY_ONEHALF,
	"¾":FullKeyList.KEY_THREEQUARTERS,
	"¿":FullKeyList.KEY_QUESTIONDOWN,
	"à":FullKeyList.KEY_AGRAVE,
	"á":FullKeyList.KEY_AACUTE,
	"â":FullKeyList.KEY_ACIRCUMFLEX,
	"ã":FullKeyList.KEY_ATILDE,
	"ä":196,
	"å":FullKeyList.KEY_ARING,
	"æ":FullKeyList.KEY_AE,
	"ç":FullKeyList.KEY_CCEDILLA,
	"è":FullKeyList.KEY_EGRAVE,
	"é":FullKeyList.KEY_EACUTE,
	"ê":FullKeyList.KEY_ECIRCUMFLEX,
	"ë":FullKeyList.KEY_EDIAERESIS,
	"ì":FullKeyList.KEY_IGRAVE,
	"í":FullKeyList.KEY_IACUTE,
	"î":FullKeyList.KEY_ICIRCUMFLEX,
	"Idiaeresis":FullKeyList.KEY_IDIAERESIS,
	"ð":FullKeyList.KEY_ETH,
	"ñ":FullKeyList.KEY_NTILDE,
	"ò":FullKeyList.KEY_OGRAVE,
	"ó":FullKeyList.KEY_OACUTE,
	"ô":FullKeyList.KEY_OCIRCUMFLEX,
	"õ":FullKeyList.KEY_OTILDE,
	"ö":214,
	"×":FullKeyList.KEY_MULTIPLY,
	"ø":FullKeyList.KEY_OOBLIQUE,
	"ù":FullKeyList.KEY_UGRAVE,
	"ú":FullKeyList.KEY_UACUTE,
	"û":FullKeyList.KEY_UCIRCUMFLEX,
	"ü":220,
	"ý":FullKeyList.KEY_YACUTE,
	"þ":FullKeyList.KEY_THORN,
	"ß":FullKeyList.KEY_SSHARP,
	"÷":FullKeyList.KEY_DIVISION,
	"ÿ":FullKeyList.KEY_YDIAERESIS,
}


#var keyListScancode = {
#	"Escape":16777217,
#	"Tab":16777218,
#	"Shift-Tab":16777219,
#	"Backspace":16777220,
#	"Return":16777221,
#	"Enter":16777222,
#	"Insert":16777223,
#	"Delete":16777224,
#	"Pause":16777225,
#	"Printscreen":16777226,
#	"SystemRequest":16777227,
#	"Clear":16777228,
#	"Home":16777229,
#	"End":16777230,
#	"LeftArrow":16777231,
#	"UpArrow":16777232,
#	"RightArrow":16777233,
#	"DownArrow":16777234,
#	"Pageup":16777235,
#	"Pagedown":16777236,
#	"Shift":16777237,
#	"Control":16777238,
#	"Meta":16777239,
#	"Alt":16777240,
#	"Capslock":16777241,
#	"Numlock":16777242,
#	"Scrolllock":16777243,
#	"F1":16777244,
#	"F2":16777245,
#	"F3":16777246,
#	"F4":16777247,
#	"F5":16777248,
#	"F6":16777249,
#	"F7":16777250,
#	"F8":16777251,
#	"F9":16777252,
#	"F10":16777253,
#	"F11":16777254,
#	"F12":16777255,
#	"F13":16777256,
#	"F14":16777257,
#	"F15":16777258,
#	"F16":16777259,
#	"MultiplyonNumpad":16777345,
#	"DivideonNumpad":16777346,
#	"SubtractonNumpad":16777347,
#	"PeriodonNumpad":16777348,
#	"AddonNumpad":16777349,
#	"Number0onNumpad":16777350,
#	"Number1onNumpad":16777351,
#	"Number2onNumpad":16777352,
#	"Number3onNumpad":16777353,
#	"Number4onNumpad":16777354,
#	"Number5onNumpad":16777355,
#	"Number6onNumpad":16777356,
#	"Number7onNumpad":16777357,
#	"Number8onNumpad":16777358,
#	"Number9onNumpad":16777359,
#	"LeftSuper(Windows)":16777260,
#	"RightSuper(Windows)":16777261,
#	"Contextmenu":16777262,
#	"LeftHyper":16777263,
#	"RightHyper":16777264,
#	"Help":16777265,
#	"LeftDirection":16777266,
#	"RightDirection":16777267,
#	"Back":16777280,
#	"Forward":16777281,
#	"Stop":16777282,
#	"Refresh":16777283,
#	"Volumedown":16777284,
#	"Mutevolume":16777285,
#	"Volumeup":16777286,
#	"BassBoost":16777287,
#	"BassUp":16777288,
#	"BassDown":16777289,
#	"TrebleUp":16777290,
#	"TrebleDown":16777291,
#	"Mediaplay":16777292,
#	"Mediastop":16777293,
#	"Previoussong":16777294,
#	"Nextsong":16777295,
#	"Mediarecord":16777296,
#	"Homepage":16777297,
#	"Favorites":16777298,
#	"Search":16777299,
#	"Standby":16777300,
#	"OpenURL/LaunchBrowser":16777301,
#	"LaunchMail":16777302,
#	"LaunchMedia":16777303,
#	"LaunchShortcut0":16777304,
#	"LaunchShortcut1":16777305,
#	"LaunchShortcut2":16777306,
#	"LaunchShortcut3":16777307,
#	"LaunchShortcut4":16777308,
#	"LaunchShortcut5":16777309,
#	"LaunchShortcut6":16777310,
#	"LaunchShortcut7":16777311,
#	"LaunchShortcut8":16777312,
#	"LaunchShortcut9":16777313,
#	"LaunchShortcutA":16777314,
#	"LaunchShortcutB":16777315,
#	"LaunchShortcutC":16777316,
#	"LaunchShortcutD":16777317,
#	"LaunchShortcutE":16777318,
#	"LaunchShortcutF":16777319,
#	"Unknown":33554431,
#	"Space":32,
#	"!":33,
#	"\"":34,
#	"#":35,
#	"$":36,
#	"%":37,
#	"&":38,
#	"'":39,
#	"(":40,
#	")":41,
#	"*":42,
#	"+":43,
#	",":44,
#	"-":45,
#	".":46,
#	"/":47,
#	"0":48,
#	"1":49,
#	"2":50,
#	"3":51,
#	"4":52,
#	"5":53,
#	"6":54,
#	"7":55,
#	"8":56,
#	"9":57,
#	":":58,
#	";":59,
#	"<":60,
#	"=":61,
#	">":62,
#	"?":63,
#	"@":64,
#	"A":65,
#	"B":66,
#	"C":67,
#	"D":68,
#	"E":69,
#	"F":70,
#	"G":71,
#	"H":72,
#	"I":73,
#	"J":74,
#	"K":75,
#	"L":76,
#	"M":77,
#	"N":78,
#	"O":79,
#	"P":80,
#	"Q":81,
#	"R":82,
#	"S":83,
#	"T":84,
#	"U":85,
#	"V":86,
#	"W":87,
#	"X":88,
#	"Y":89,
#	"Z":90,
#	"[":91,
#	"\\":92,
#	"]":93,
#	"^":94,
#	"_":95,
#	"LeftQuote":96,
#	"{":123,
#	"|":124,
#	"}":125,
#	"~":126,
#	"NoBreakSpace":160,
#	"ExcalmDown":161,
#	"¢":162,
#	"Sterling":163,
#	"Currency":164,
#	"Yen":165,
#	"¦":166,
#	"§":167,
#	"¨":168,
#	"©":169,
#	"Feminine":170,
#	"«":171,
#	"»":172,
#	"‐":173,
#	"®":174,
#	"Macron":175,
#	"°":176,
#	"±":177,
#	"²":178,
#	"³":179,
#	"´":180,
#	"µ":181,
#	"Paragraph":182,
#	"·":183,
#	"¬":184,
#	"¹":185,
#	"♂":186,
#	"GuillemotRight":187,
#	"¼":188,
#	"½":189,
#	"¾":190,
#	"¿":191,
#	"à":192,
#	"á":193,
#	"â":194,
#	"ã":195,
#	"ä":196,
#	"å":197,
#	"æ":198,
#	"ç":199,
#	"è":200,
#	"é":201,
#	"ê":202,
#	"ë":203,
#	"ì":204,
#	"í":205,
#	"î":206,
#	"Idiaeresis":207,
#	"ð":208,
#	"ñ":209,
#	"ò":210,
#	"ó":211,
#	"ô":212,
#	"õ":213,
#	"ö":214,
#	"×":215,
#	"ø":216,
#	"ù":217,
#	"ú":218,
#	"û":219,
#	"ü":220,
#	"ý":221,
#	"þ":222,
#	"ß":223,
#	"÷":247,
#	"ÿ":255,
#}

func hasLowercase(code: int):
	return keyListLowercase.values().has(code)

#func getScancodeFromString(name, debug=false):
#	if keyListScancode.has(str(name)):
#		if debug:
#			print("Scancode OK:"+name)
#		return keyListScancode.get(str(name))
#	else:
#		if debug:
#			print("Scancode Key not found:"+ name)
#		return FullKeyList.KEY_UNKNOWN


func getUnicodeFromString(name:String, debug=false)-> int:
	if keyListUnicode.has(str(name)):
		if debug:
			print("Unicode OK:"+name)
		return keyListUnicode.get(str(name))
	else:
		if debug:
			print("Unicode Key not found:"+ name)
		return FullKeyList.KEY_UNKNOWN

func _ready():
	pass # Replace with function body.
